# Generated by Django 5.0.1 on 2025-05-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="conversation_history",
            field=models.JSONField(
                default=list, help_text="List of conversation messages"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.JSONField(help_text="List of order items as JSON"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.JSONField(help_text="Shipping address as JSON"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=models.JSONField(default=list, help_text="List of available sizes"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="shop_catego_slug_5ac49f_idx"),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["session_id"], name="shop_chatse_session_a3955d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="shop_order_order_n_db1214_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user"], name="shop_order_user_id_e5ca77_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="shop_produc_slug_76971b_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "gender"], name="shop_produc_categor_6affb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "user"], name="shop_review_product_f098d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["firebase_uid"], name="shop_userpr_firebas_982211_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["email"], name="shop_userpr_email_8799d6_idx"),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(fields=["user"], name="shop_wishli_user_id_1c58f1_idx"),
        ),
    ]
